#!/usr/bin/env bash
# a script that installs nginx on the web-01 server

# update machine
sudo apt-get update

# install nginx
sudo apt-get install -y nginx

# write hello world to html file
echo "Hello World!" > /var/www/html/task1.html

# restart nginx server
service nginx restart
