#!/usr/bin/env bash
# this script configures an nginx server to have
# a custom 404 page

sudo apt-get update
sudo apt-get install -y nginx

REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
FL="/etc/nginx/sites-available/default"

ERR_FL="/usr/share/nginx/html/404error.html"
STR="Ceci n'est pas une page"
ERR_REDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"

sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "37i\ $REDIRECT" "$FL"

echo "$STR" > "$ERR_FL"
sudo sed -i "37i\ $ERR_REDIRECT" "$FL"

sudo service nginx restart
