#!/usr/bin/env bash
# script that configures an nginx server with a custom header

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html

REDIR="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
ERR_RED="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
CUSTOM_H="\n\tadd_header X-Served-By \$hostname;\n"

FL="/etc/nginx/sites-available/default"
ERR_FL="/usr/share/nginx/html/404error.html"

FOUR04="Ceci n'est pas une page"

sudo sed -i "37i\ $REDIR" "$FL"

echo "$FOUR04" > "$ERR_FL"

sudo sed -i "37i\ $ERR_RED" "$FL"

sudo sed -i "37i\ $CUSTOM_H" "$FL"
sudo service nginx restart
