#!/usr/bin/env bash
# script that installs and configs the hAproxy on the lb-0a server
# to send traffic to web-01 and web-02 using roundrobin algorithm

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
defaults
	mode http
	timeout client 15s
	timeout connect 10s
	timeout server 15s
	timeout http-request 10s

frontend kisotu-frontend
        bind *:80
        mode http
        default_backend kisotu-backend

backend kisotu-backend
        balance roundrobin
        server 531653-web-01 54.172.184.51:80 check
        server 531653-web-02 52.90.22.219:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
