#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# Only display username, user id, Home dir path for the user

while read -r psdw;
do
   echo "$psdw" | cut -d '-' -f1,3,6
done < "/etc/passwd"
