#!/usr/bin/env bash
# Bash script that displays:
#    The content of the current directory
#    in a list format
#    Where only the part of the name after the first dash is displayed

listdir=$(ls)
for k in $listdir;
do
   echo "$k" | cut -d '-' -f2
done
